# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: Designs By
title-normal: Wasabi
email: designsbywasabi@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/DesignsByWasabi" # the subpath of your site, e.g. /blog
url: "https://designsbywasabi.github.io" # the base hostname & protocol for your site
author: Christopher Acosta
phone: (210) 612-5218

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages" 
tiles-count: 6

# Social settings
github_url: https://github.com/DesignsByWasabi
instagram_url: https://instagram.com
# Build settings
markdown: kramdown
